let money = 3000;
let income = "вторая работа";
let addExpenses = "Налоги, Кредит, Интернет";
let deposit = true;
let mission = 50000;
let period = 12;
console.log(typeof money);
console.log(typeof mission);
console.log(typeof deposit);
console.log(addExpenses.length);
console.log("Период равен " + period + " месяцев");
console.log("Цель заработать " + mission + " долларов");
console.log(addExpenses.toLowerCase(addExpenses.split(", ")));
let budgetDay = 3000 / 30;
console.log(budgetDay);
